# CoCalc Travis-CI Configuration File
sudo: required
dist: xenial

# no need to build all branches
branches:
  only:
    - master

# there is no single language, but python is ok
language: "python"

# travis supports 8 and 11 (as of winter 2018)
node_js:
  - "8"

# we want our database
services:
  - postgresql

# specify postgres version and additional linux packages here
addons:
  postgresql: "10"
  apt:
    update: true
    packages:
      - "python-pip"
      - "python3-pip"
      - "python3-pytest"

# Travis supports "global" and "build matrix" variables
# http://docs.travis-ci.com/user/environment-variables/
env:
  global: # note: we cannot use $VARs here
    - REPORTER=list # for mocha tests
    - PGUSER='smc'
  matrix:
    # testing build modes
    - NODE_ENV=production
    - NODE_ENV=development
    - CC_COMP_ENV=true KUCALC_MODE=true

before_install: []

# installation and setup
before_script:
  - "source /etc/lsb-release"
  - "pip -V"
  - "pip3 -V"
  - "python -V"
  - "node --version"
  - "pytest --version"
  - 'export PGHOST="$TRAVIS_BUILD_DIR/src/dev/project/postgres_data/socket"'
  - "python2 $TRAVIS_BUILD_DIR/src/dev/project/start_postgres.py &"
  - "sleep 10" # for starting up postgres in the background (db init, etc.)

# the setup & compilation of CoCalc
# if broken, this will also trigger a test failure, i.e. that's also a test
install:
  - "cd src"
  - "source smc-env"
  - 'if [[ $KUCALC_MODE != "true" ]]; then npm run make; fi'
  - 'if [[ $KUCALC_MODE  = "true" ]]; then python install.py webapp build; fi'
  #- "cd $TRAVIS_BUILD_DIR/src/smc-webapp/; npm install mocha" # why necessary?

# This is the actual testing, which runs in the same directory where `before_script` did end up in.
# A non-zero exit code indicates a failure.
# npm test is the usual, and coverage reporting is disabled
script:
  - "$TRAVIS_BUILD_DIR/.travis-test.sh"

# send coverage report over to https://coveralls.io
#after_success:
#  - if [[ $MODE = "server" ]]; then sh -c 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'; fi

notifications:
  email:
    recipients:
      - "hsy@sagemath.com"
    on_success: change
    on_failure: change
