# CoCalc Travis-CI Configuration File
sudo: required
dist: xenial

# no need to build all branches
branches:
  only:
    - master

# there is no single language, but python is ok
language: "python"

# travis supports 8 and 11 (as of winter 2018)
node_js:
  - "8"

# we want our database
services:
  - postgresql

# specify postgres version and additional linux packages here
addons:
  postgresql: "10"
  apt:
    update: true
    packages:
      - "python-pip"
      - "python3-pip"
      - "python3-pytest"

# Travis supports "global" and "build matrix" variables
# http://docs.travis-ci.com/user/environment-variables/
env:
  global:
    - REPORTER=list # for mocha tests
    - PGUSER='smc'
    - PGHOST='/home/travis/build/sagemathinc/cocalc/src/dev/project/postgres_data/socket'
  matrix:
    - MODE=misc
    - MODE=hub # hub, postgres, etc.
    #- MODE=util
    #- MODE=sagews
    #- MODE=server

before_install: []

# installation and setup
before_script:
  - "source /etc/lsb-release"
  - "pip -V"
  - "pip3 -V"
  - "python -V"
  - "node --version"
  - "pytest --version"
  - "python2 ~/build/sagemathinc/cocalc/src/dev/project/start_postgres.py &"
  - "sleep 5"

# the setup & compilation of CoCalc
# if broken, this will also trigger a test failure, i.e. that's also a test
install:
  - "cd src"
  - "source smc-env"
  - "npm run make"

# This is the actual testing, which runs in the same directory where `before_script` did end up in.
# A non-zero exit code indicates a failure.
# npm test is the usual, and coverage reporting is disabled
script:
  - 'if [[ $MODE = "sagews" ]]; then cd ~/build/sagemathinc/cocalc/src/smc_sagews/smc_sagews/; python -m pytest tests/; fi'
  - 'if [[ $MODE = "webapp" ]]; then cd ~/build/sagemathinc/cocalc/src/smc-webapp/; npm run test; fi'
  - 'if [[ $MODE = "server" ]]; then npm run coveralls; fi'
  - 'if [[ $MODE = "util"   ]]; then cd ~/build/sagemathinc/cocalc/src/smc-util/; npm test; fi'
  - 'if [[ $MODE = "misc"   ]]; then cd ~/build/sagemathinc/cocalc/src/smc-util/; export NODE_ENV=mocha-test && SMC_TEST=true node_modules/.bin/mocha --reporter ${REPORTER:-progress} test/misc-test.coffee test/synctable-test.coffee; fi'
  - 'if [[ $MODE = "hub"  ]]; then cd ~/build/sagemathinc/cocalc/src/smc-hub/; npm run testpg; npm run testmisc; npm run testkucalc; fi'

# send coverage report over to https://coveralls.io
#after_success:
#  - if [[ $MODE = "server" ]]; then sh -c 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'; fi

notifications:
  email:
    recipients:
      - "hsy@sagemath.com"
    on_success: change
    on_failure: change
